Repository AY2425S1-CS2103T-F12-4/tp, pull requests merged in 2024-11, with the labels that each got.

#126 Fix bug where password do not clear after failed attempt
  src/main/java/seedu/address/ui/PasswordPromptDialog.java
Labels: alpha-bug

#140 Sync command summary
  docs/_markbind/variables.md
  src/main/java/seedu/address/commons/util/CommandSummaryUtil.java
  src/main/java/seedu/address/commons/util/MarkdownUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/commons/util/CommandSummaryUtilTest.java
  src/test/java/seedu/address/commons/util/MarkdownUtilTest.java
Labels: priority.High

#139 Fix mass delete
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#106 Update short commands
  .gitignore
  docs/UserGuide.md
  docs/_markbind/variables.md
  docs/team/rachelyeohm.md
  src/main/java/seedu/address/commons/util/CommandSummaryUtil.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/QuitCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/KeyBindController.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/CommandSummaryUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/QuitCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#154 Fix Windows issue on deleting files
  src/main/java/seedu/address/ui/PasswordPromptDialog.java
Labels: alpha-bug

#147 Update command message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: priority.Medium

#155 Fix bug with edit 1 -t
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: alpha-bug

#157 Clear password field on wrong password input
  src/main/java/seedu/address/ui/PasswordPromptDialogController.java
Labels: alpha-bug

#223 Change addressbook.json to vbook.json
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High
